version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    container_name: notes_challenge_db
    environment:
      POSTGRES_USER: ${DB_USERNAME:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin123}
      POSTGRES_DB: ${DB_NAME:-notesdb}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-admin} -d ${DB_NAME:-notesdb}"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
    driver: local